#!/bin/bash
# Open the desired chart in Trading View.

# Set color
RESET_COLOR="\e[0m"
RED="\e[31m"
GREEN="\e[32m"

if [[ ${1} ]]
	then
		which firefox > /dev/null
			if [[ ${?} -eq 0 ]]
				then
					firefox --new-window "https://www.tradingview.com/chart?symbol=BINANCE%3A${1}"
					notify-send 'Opening TradingView 📊'

				else
					echo "${RED}Firefox is not installed on this system !${RESET_COLOR}"
					exit 1
	else
		echo -e "${RED}Please enter a symbol (ex:BTCUSDT)\nDefault exchange is Binance.${RESET_COLOR}"
fi
