#!/bin/bash
## Open the desired chart in Trading View.

RESET_COLOR="\e[0m"
RED="\e[31m"
BOLD="\e[1m"

REQUIREMENTS="firefox"

## Check if root.
if [ "$EUID" -eq "0" ]
	then
		echo -e "${RED}This must not be runned as root !${RESET_COLOR}"
		exit 1
	else
		which ${REQUIREMENTS} > /dev/null
		if [[ ${?} -eq "0" ]]
			then
				if [[ ${1} ]]
					then
						notify-send 'Opening TradingView 📊'
						firefox --new-window "https://www.tradingview.com/chart?symbol=BINANCE%3A${1}"
					else
						echo -e "${RED}Please enter a symbol (ex:BTCUSDT)\nDefault exchange is Binance.${RESET_COLOR}"
				fi
			else
				echo -e "${RED}To run this program, you need the following package(s) installed: ${BOLD}${REQUIREMENTS}${RESET_COLORS}"
				exit 1
		fi
fi
