#!/bin/bash
#..:Display favorites crypto prices (in USD):..

clear

echo -e "\e[33mBTC:\e[0m $(curl -s https://api.coinbase.com/v2/prices/BTC-USD/buy | cut -d\: -f5 | cut -d\" -f2)\e[32m$"
echo -e "\e[36mETH:\e[0m $(curl -s https://api.coinbase.com/v2/prices/ETH-USD/buy | cut -d\: -f5 | cut -d\" -f2)\e[32m$"
