#!/bin/bash

REQUIREMENTS='redshift'

checkTheme()
{
	if [[ -e /usr/share/themes/Adwaita-dark ]] && \
	[[ -e /usr/share/themes/HighContrast ]] && \
	[[ -e /usr/share/icons/Papirus-Dark ]] && \
	[[ -e /usr/share/icons/Papirus-Light ]] && \
	[[ -e /usr/share/icons/Adwaita ]] && \
	[[ -e /usr/share/icons/Simp1e ]]
		then
			echo -e "\e[32mThemes found..."
		else
			echo -e "\e[31mThemes missing..."
			exit 1
	fi
}

setLightTheme()
{
	xfconf-query -c xsettings -p /Net/ThemeName -s 'High Contrast'
	xfconf-query -c xsettings -p /Net/IconThemeName -s 'Papirus-Light'
	xfconf-query -c xsettings -p /Gtk/CursorThemeName -s 'Adwaita'
	gsettings set org.gnome.desktop.interface color-scheme prefer-light
	[[ -e ~/.config/rofi/config.rasi ]] && [[ -e ~/.config/rofi/light.rasi ]]
	sed -i 's#@theme "~/.config/rofi/dark.rasi"#@theme "~/.config/rofi/light.rasi"#g' \
	~/.config/rofi/config.rasi
}

setDarkTheme()
{
	xfconf-query -c xsettings -p /Net/ThemeName -s 'Adwaita-dark'
	xfconf-query -c xsettings -p /Net/IconThemeName -s 'Papirus-Dark'
	xfconf-query -c xsettings -p /Gtk/CursorThemeName -s 'Simple'
	gsettings set org.gnome.desktop.interface color-scheme prefer-dark
	[[ -e ~/.config/rofi/config.rasi ]] && [[ -e ~/.config/rofi/dark.rasi ]]
	sed -i 's#@theme "~/.config/rofi/light.rasi"#@theme "~/.config/rofi/dark.rasi"#g' \
	~/.config/rofi/config.rasi
}

relaunchApp()
{
	## Restart xfce component
	xfwm4 -r&
	xfce4-panel -r&

	## Restart clipman to update the taskbar icon.
	if [[ $(pidof xfce4-clipman) != "" ]]
		then
			killall xfce4-clipman
			xfce4-clipman&
	fi

	## Restart Telegram to update the taskbar icon.
	if [[ $(pidof Telegram) != "" ]]
		then
			killall Telegram
			[[ -f /opt/Telegram/Telegram ]] && /opt/Telegram/Telegram&
	fi
}

PERIOD=$(redshift -p 2>/dev/null | grep "Period" | cut -d ' ' -f 2)

if [[ ${PERIOD} == 'Daytime' ]]
	then
		setLightTheme
		relaunchApp
		echo "☀️ It's currently the day, setting the light theme..."
elif [[ ${PERIOD} == 'NightTime' ]]
	then
		setDarkTheme
		relaunchApp
		echo "🌙 It's currently the night, setting the dark theme..."
	else
		echo "Unable to get the current time..."
		exit 1
fi
