#!/bin/bash
## Switch to light/dark themes if it's the day or the night (made for Xfce).
## Typically you would run this program in a cronjob.

REQUIREMENTS='redshift'
#LIGHT_THEME="Adwaita"
#DARK_THEME="Adwaita-dark"
LIGHT_THEME="Flat-Remix-GTK-Blue-Light-Solid"
DARK_THEME="Flat-Remix-GTK-Blue-Darkest-Solid"
ICON_LIGHT="ePapirus-Light"
ICON_DARK="ePapirus-Dark"
LIGHT_CURSOR="Adwaita"
DARK_CURSOR="Simp1e"

checkTheme()
{
	if [[ -e /usr/share/themes/${DARK_THEME} ]] && \
	[[ -e /usr/share/themes/${LIGHT_THEME} ]] && \
	[[ -e /usr/share/icons/Papirus-Dark ]] && \
	[[ -e /usr/share/icons/Papirus-Light ]] && \
	[[ -e /usr/share/icons/${LIGHT_THEME} ]] && \
	[[ -e /usr/share/icons/Simp1e ]]
		then
			echo -e "\e[32mThemes found..."
		else
			echo -e "\e[31mThemes missing..."
			exit 1
	fi
}

setLightTheme()
{
    ## Set xfce theme
	xfconf-query -c xsettings -p /Net/ThemeName -s "${LIGHT_THEME}"
	xfconf-query -c xsettings -p /Net/IconThemeName -s "${ICON_LIGHT}"
    ## Set cursor theme
	xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "${LIGHT_CURSOR}"
    ## Set GTK theme
	gsettings set org.gnome.desktop.interface color-scheme prefer-light
#	[[ -e ~/.config/rofi/config.rasi ]] && [[ -e ~/.config/rofi/light.rasi ]]
#	sed -i 's#@theme "~/.config/rofi/dark.rasi"#@theme "~/.config/rofi/light.rasi"#g' \
#	~/.config/rofi/config.rasi
}

setDarkTheme()
{
    ## Set xfce theme
	xfconf-query -c xsettings -p /Net/ThemeName -s "${DARK_THEME}"
	xfconf-query -c xsettings -p /Net/IconThemeName -s "${ICON_LIGHT}"
    ## Set cursor theme
	xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "${DARK_CURSOR}"
    ## Set GTK theme
	gsettings set org.gnome.desktop.interface color-scheme prefer-dark
#	[[ -e ~/.config/rofi/config.rasi ]] && [[ -e ~/.config/rofi/dark.rasi ]]
#	sed -i 's#@theme "~/.config/rofi/light.rasi"#@theme "~/.config/rofi/dark.rasi"#g' \
#	~/.config/rofi/config.rasi
}

relaunchApp()
{
	## Restart xfce component
	xfwm4 -r&
	xfce4-panel -r&

	## Restart clipman to update the taskbar icon.
	if [[ $(pidof xfce4-clipman) != "" ]]
		then
			killall xfce4-clipman
			xfce4-clipman&
	fi

	## Restart Telegram to update the taskbar icon.
	if [[ $(pidof Telegram) != "" ]]
		then
			killall Telegram
			[[ -f /opt/Telegram/Telegram ]] && /opt/Telegram/Telegram&
	fi
}

PERIOD=$(redshift -p 2>/dev/null | grep "Period" | cut -d ' ' -f 2)

if [[ ${PERIOD} == 'Daytime' ]]
	then
		setLightTheme
		relaunchApp
		echo "☀️ It's currently the day, setting the light theme..."
elif [[ ${PERIOD} == 'Night' ]]
	then
		setDarkTheme
		relaunchApp
		echo "🌙 It's currently the night, setting the dark theme..."
	else
		echo "Unable to get the current time..."
		exit 1
fi
