#!/usr/bin/env bash
## Copy emoji to your clipboard.
RED="\e[31m"
REQUIREMENTS="xclip rofi"
DMENU="rofi -dmenu -i -p"
EMOJI_FILE="${HOME}/.emoji"

if ! which ${REQUIREMENTS}>/dev/null
    then
        echo -e "${RED}To run this script, you need: ${REQUIREMENTS}"
        exit 1
fi

cat ${EMOJI_FILE}\
| ${DMENU} "Emoji:"\
|cut -d " " -f 1\
|xclip -selection clipboard
