#!/bin/bash
# Free swap space and caches.

RESET_COLOR="\e[0m"
BOLD="\e[1m"
BLUE="\e[34m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"

USER_HOME="/home/lespink"

function CACHE_DIR()
{
	if [[ -d /root/.cache ]]
		then
			echo -e "${YELLOW}Removing the ${BOLD}root ${RESET_COLOR}${YELLOW}cache directory...${RESET_COLOR}"
			rm -vrf /root/.cache 2>/dev/null
	elif [[ -d ${USER_HOME}/.cache ]]
		then
			echo -e "${YELLOW}Removing the ${BOLD}user ${RESET_COLOR}${YELLOW}cache directory...${RESET_COLOR}"
			rm -vrf ${USER_HOME}/.cache 2>/dev/null
	elif [[ -d ${USER_HOME}/.mozilla/firefox/*/cache* ]]
		then
			echo -e "${YELLOW}Removing the ${BOLD}firefox ${RESET_COLOR}${YELLOW}cache directory...${RESET_COLOR}"
			rm -vrf ${USER_HOME}/.mozilla/firefox/*/cache* 2>/dev/null
	elif [[ -d ${USER_HOME}/.config/Binance/Partitions/binance.app/Cache/* ]]
		then
			echo -e "${YELLOW}Removing the ${BOLD}Binance ${RESET_COLOR}${YELLOW}cache directory...${RESET_COLOR}"
			rm -vrf ${USER_HOME}/.config/Binance/Partitions/binance.app/Cache/* 2>/dev/null
	elif [[ -d ${USER_HOME}/.config/molotov/Cache/* ]]
		then
			echo -e "${YELLOW}Removing the ${BOLD}Molotov ${RESET_COLOR}${YELLOW}cache directory...${RESET_COLOR}"
			rm -vrf ${USER_HOME}/.config/molotov/Cache/* 2>/dev/null
	fi
}

function SWAP_SPACE()
{
	sync
	swapoff -av
	swapon -av
	sync
	echo 3>/proc/sys/vm/drop_caches
}

SWAP_SPACE

# Check if root
if [ "$EUID" -ne "0" ]
    then
        echo -e "${RED}This script must be runned as root !${RESET_COLOR}"
        exit 1
	else
		echo -e "${RED}Please close all application currently running ! ${RESET_COLOR}"
		read
		CACHE_DIR
			if [[ $(swapon --show) == "" ]]
				then
					echo -e "${YELLOW}Swap device not found on this system.${RESET_COLOR}"
				else
					echo -e "${YELLOW}Emptying ${BOLD}swap ${RESET_COLOR}${YELLOW}space and synchronizing cached writes to persistent storage...${RESET_COLOR}"
					SWAP_SPACE
			fi
fi
