#!/bin/bash
# Free swap space and caches.
clear

# Set color
RESET_COLOR="\e[0m"
BOLD="\e[1m"
BLUE="\e[34m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"

# Check if root
if [ "$EUID" -ne 0 ]
    then
        echo -e "${RED}This script must be runned as root${RESET_COLOR}"
        exit
fi

function CACHE_DIR()
{
 	# cache
	rm -rf /root/.cache
	rm -rf /home/.cache
	rm -rf /root/.mozilla/firefox/*/cache2
}

function SWAP_SPACE()
{
 	# swap
	sync
	swapoff -av
	swapon -av
	sync
	echo 3 > /proc/sys/vm/drop_caches
}

echo -e "${RED}Please close all application currently running ! ${RESET_COLOR}"
read
echo -e "${YELLOW}Removing the cache directory...${RESET_COLOR}"
CACHE_DIR
echo -e "${YELLOW}Emptying swap space and synchronizing cached writes to persistent storage...${RESET_COLOR}"
SWAP_SPACE
