#!/bin/bash
# .:: Say hi,date ::.

DATE=$(date "+%d %B")
TIME=$(date "+%H:%M:%S")
DAY=$(date "+%A")
DOY=$(date "+%j")
YEAR=$(date "+%Y")
UPTIME_PRETTY=$(uptime -p | sed 's/,//;s/up //')

if [[ $? -eq 0 ]]
	then
		cowsay -f $(ls /usr/share/cowsay/cows/*|shuf|head -n 1) "Hi"
		echo -e "We are the \e[35m\e[1m${DATE}\e[0m and it's \e[35m\e[1m${TIME}\e[0m.\nThis \e[35m\e[1m${DAY}\e[0m is the day \e[35m\e[1m${DOY}\e[0m of the year \e[35m\e[1m${YEAR}\e[0m\n\nI'm up since \e[35m\e[1m${UPTIME_PRETTY}\e[0m"
		read
	else
		echo -e "\e[31mError $RET\e[0m"
fi

read
