#!/bin/bash

# LOFI
LIVE_1='https://www.youtube.com/watch?v=5qap5aO4i9A' # lofi hip hop radio - beats to realax/study to
LIVE_2='https://www.youtube.com/watch?v=DWcJFNfaw9c' # lofi hip hop  - beats to sleep/chill to
LIVE_3='https://www.youtube.com/watch?v=rc9cjjEun_k' # lofi hip hop - beats to sleep/study/relax to
LIVE_4='https://www.youtube.com/watch?v=-5KAN9_CzSA' # cofee shop radio // 24/7 lofi hip hop beats
LIVE_5='https://www.youtube.com/watch?v=PdEl1Zi37v4' # kei morito - lofi Tokyo
LIVE_6='https://www.youtube.com/watch?v=5yx6BWlEVcY' # Chillhop Radio - jazzy & lofi hip hop beats
LIVE_7='https://www.youtube.com/watch?v=7NOSDKb0HlU' # lofi hip hop  - beats to study/relax to
# RELAX/MEDITATION
LIVE_8='https://www.youtube.com/watch?v=SjQUF39sRnc' # Beautiful Relaxing Music, Peaceful Soothing Instrumental Music, with Guitar "Forest Calm" Tim Janis

if [[ ${1} -eq 1 ]]
	then
		mpv --no-video $LIVE_1
elif [[ ${1} -eq 2 ]]
	then
		mpv --no-video $LIVE_2
elif [[ ${1} -eq 3 ]]
	then
		mpv --no-video $LIVE_3
elif [[ ${1} -eq 4 ]]
	then
		mpv --no-video $LIVE_4
elif [[ ${1} -eq 5 ]]
	then
		mpv --no-video $LIVE_5
elif [[ ${1} -eq 6 ]]
	then
		mpv --no-video $LIVE_6
elif [[ ${1} -eq 7 ]]
	then
		mpv --no-video $LIVE_7
elif [[ ${1} -eq 8 ]]
	then
	mpv --no-video $LIVE_8
	else
		echo 'Please enter a radio number (1-8)'
		exit 1
fi

