#!/bin/bash
clear

# LOFI
LIVE_1='https://www.youtube.com/watch?v=5qap5aO4i9A' # Relax/study
LIVE_2='https://www.youtube.com/watch?v=DWcJFNfaw9c' # Sleep/chill
LIVE_3='https://www.youtube.com/watch?v=rc9cjjEun_k' # Sleep/study/relax
LIVE_4='https://www.youtube.com/watch?v=-5KAN9_CzSA' # cofee shop radio 24/7
LIVE_5='https://www.youtube.com/watch?v=PdEl1Zi37v4' # kei morito
LIVE_6='https://www.youtube.com/watch?v=5yx6BWlEVcY' # Jazzy & beats
LIVE_7='https://www.youtube.com/watch?v=7NOSDKb0HlU' # Study/relax
# RELAX/MEDITATION
LIVE_8='https://www.youtube.com/watch?v=SjQUF39sRnc' # Relaxing Music

if [[ ${1} -eq 1 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_1
elif [[ ${1} -eq 2 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_2
elif [[ ${1} -eq 3 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_3
elif [[ ${1} -eq 4 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_4
elif [[ ${1} -eq 5 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_5
elif [[ ${1} -eq 6 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_6
elif [[ ${1} -eq 7 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_7
elif [[ ${1} -eq 8 ]]
	then
		killall -wq mpv
		mpv --no-video $LIVE_8
	else
		echo -e '\e[31mPlease enter a live ID (1-8)'
fi
