#!/bin/bash -x
# .:: Choose between different live radio hosted on youtube :..

#1='https://www.youtube.com/watch?v=5qap5aO4i9A' # lofi hip hop radio - beats to realax/study to
#2='https://www.youtube.com/watch?v=DWcJFNfaw9c' # lofi hip hop radio - beats to sleep/chill to
#3='https://www.youtube.com/watch?v=rc9cjjEun_k' # lofi hip hop - beats to sleep/study/relax to
#4='https://www.youtube.com/watch?v=-5KAN9_CzSA' # cofee radio shop // 24/7 lofi hip hop beats
#5='https://www.youtube.com/watch?v=PdEl1Zi37v4' # kei morito - lofi Tokyo
#6='https://www.youtube.com/watch?v=5yx6BWlEVcY' # Chillhop Radio - jazzy & lofi hip hop beats
#7='https://www.youtube.com/watch?v=7NOSDKb0HlU' # lofi hip hop radio - beats to study/relax to



if [[ ${1} ]]
	then
		mpv --no-video "$1"
	else
		echo 'Please enter a radio number (1-7)'
fi
