#!/bin/bash
## Metasploit framework launcher.

REQUIREMENTS="msfconsole"

## Color
RESET_COLOR="\e[0m"
RED="\e[31m"

which ${REQUIREMENTS} > /dev/null
if [[ ${?} -eq "0" ]]
	then
		## Disable Ctrl-Z
		trap "" TSTP
		/usr/bin/msfconsole
	else
		echo "${RED}The Metasploit framework is not installed on this system !${RESET_COLOR}"
fi
