#!/bin/bash
# Metasploit framework launcher.

which msfconsole>/dev/null
if [[ ${?} -eq 0 ]]
	then
		# Disable Ctrl-Z
		trap "" TSTP
		/usr/bin/msfconsole
	else
		echo "\e[31mMetasploit is not installed on this system !\e[0m"
fi
