#!/usr/bin/env bash
## Metasploit framework launcher.

## A launcher is needed since you can't background a session.
## (Ctrl+Z background the shell process instead)

REQUIREMENTS="msfconsole"

if ! which ${REQUIREMENTS}>/dev/null
	then
		echo "The Metasploit framework is not installed on this system!"
		exit 1
	else
		## Disable Ctrl-Z
		trap "" TSTP
		/usr/bin/msfconsole
fi
