#!/bin/bash
## Set colors.
RC="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"
BLUE="\e[34m"

WARN="${RED}${BOLD} [-]${RC}"
INFO="${BLUE}${BOLD} [*]${RC}"
GOOD="${GREEN}${BOLD} [+]${RC}"

INTERFACE="$(ifconfig | head -n 1 | awk {'print $1'} | cut -d ':' -f 1)"

REQUIREMENTS="ethtool ifconfig"
which ethtool > /dev/null

if [[ ${?} -ne "0" ]]
	then
		echo -e "${WARN} \n To run this program, you need the following packages installed: ${REQUIREMENTS}\n${WARN} Exiting...\n"
		exit 1
	else
		echo -e "${GREY}${INTERFACE}: ${GREEN}$(ethtool ${INTERFACE} | grep Speed | awk {'print $2'})"
fi
