#!/bin/bash
## Get the network speed of the desired interface.

## Set colors.
RC="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"
BLUE="\e[34m"
GREY="\e[37m"

WARN="${RED}${BOLD} [-] ${RC}"
INFO="${BLUE}${BOLD} [*] ${RC}"
GOOD="${GREEN}${BOLD} [+] ${RC}"

INTERFACE="$(ifconfig | head -n 1 | awk {'print $1'} | cut -d ':' -f 1)"

REQUIREMENTS="ethtool ifconfig"
which ethtool > /dev/null

if [[ ${?} -ne "0" ]]
	then
		echo -e "${WARN} \n To run this program, you need the following packages installed: ${REQUIREMENTS}\n${WARN} Exiting...\n"
		exit 1
	else
		echo -e "${BOLD}${GREY}${INTERFACE}: ${BOLD}${GREEN}$(ethtool ${INTERFACE} 2>/dev/null | grep Speed | awk {'print $2'})"
fi

