#!/bin/bash
## Simple note taking.

RC="\e[0m"
BOLD="\e[1m"
YELLOW="\e[33m"
RED="\e[31m"

NOTE_FILE="${HOME}/.note"

## Check if root.
if [ "$EUID" -eq "0" ]
	then
		echo -e "${RED}This script must not be run as root\nExiting...!${RC}"
		exit 1
	else
		if [[ -f ${NOTE_FILE} ]]
			then
				${EDITOR} ${NOTE_FILE}
			else
				echo -e "${YELLOW}Note file note not found, do you want to create one? (Y/n)${RCS}"
				read CREATE_NOTE_FILE
				if [[ ${CREATE_NOTE_FILE} == "n" ]]
					then
						exit
					else
						touch ${NOTE_FILE}
						${EDITOR} ${NOTE_FILE}
				fi
		fi
fi
