#!/bin/bash
 ## Script to send notifications since crontab dosen't work with notify-send.
DATE=$(date '+%H%M')
TIME="2130" ## Time to go to bed.
SLEEP="600" ## 10 min.
while true
	do
		if [[ ${DATE} -ge ${TIME} ]]
			then
				notify-send -u critical " 💤 Time to go to bed! 💤 "
			else
				exit 0
		fi
		sleep ${SLEEP}
done
