#!/bin/bash
## Simple password manager.
## Store your passwords inside a local text file, gpg encrypted.
## NEVER TRUST ONLINE PASSWORDS MANAGER!

RESET_COLOR="\e[0m"
YELLOW="\e[33m"
BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"

REQUIREMENTS="shred gpg" ## And a CLI editor of your choice.

ENCRYPTED_PASS_FILE="/home/$USER/.pass.gpg"
UNCRYPTED_PASS_FILE="/home/$USER/.pass"

if [ "$EUID" -eq "0" ]
	then
		echo -e "${RED}This must not be run as root!\nExiting...${RESET_COLOR}"
		exit 1
	else
		if [[ -f /home/${USER}/.pass.gpg ]]
			then
				which ${REQUIREMENTS} > /dev/null
					if [[ ${?} -eq "0" ]]
						then
							gpg -d -o ${UNCRYPTED_PASS_FILE} --no-symkey-cache ${ENCRYPTED_PASS_FILE}
							${EDITOR} ${UNCRYPTED_PASS_FILE}
							gpg -c --cipher-algo AES256 --no-symkey-cache ${UNCRYPTED_PASS_FILE}
							shred -fuzv ${UNCRYPTED_PASS_FILE}
						else
							echo -e "${RED}To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}\nExiting...${RESET_COLORS}"
					fi
			else
				echo -e "${YELLOW}Note file note not found, do you want to create one? (Y/n)${RESET_COLORS}"
				read CREATE_UNCRYPTED_PASS_FILE
					if [[ ${CREATE_UNCRYPTED_PASS_FILE} == "n" ]]
						then
							exit
						else
							touch ${UNCRYPTED_PASS_FILE}
							${EDITOR} ${UNCRYPTED_PASS_FILE}
					fi
		fi
fi
