#!/bin/bash
## Simple password manager.
## Store your passwords inside a local text file, gpg encrypted.
## NEVER TRUST ONLINE PASSWORDS MANAGER !

## Colors.
RESET_COLOR="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"

REQUIREMENTS="shred gpg" ## And a CLI editor of your choice.

ENCRYPTED_PASS_FILE="/home/$USER/.pass.gpg"
UNCRYPTED_PASS_FILE="/home/$USER/.pass"

## Check if root.
if [ "$EUID" -eq "0" ]
	then
		echo -e "${RED}This must not be runned as root !${RESET_COLOR}"
		exit 1
	else
		if [[ -f /home/${USER}/.pass.gpg ]]
			then
				which ${REQUIREMENTS} > /dev/null
					if [[ ${?} -eq "0" ]]
						then
							gpg -d -o ${UNCRYPTED_PASS_FILE} --no-symkey-cache ${ENCRYPTED_PASS_FILE}
							${EDITOR} ${UNCRYPTED_PASS_FILE}
							gpg -c --cipher-algo AES256 --no-symkey-cache ${UNCRYPTED_PASS_FILE}
							shred -fuzv ${UNCRYPTED_PASS_FILE}
						else
							echo -e "${RED}To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RESET_COLORS}"
					fi
			else
				echo -e "${RED}To run this program, you need the following package(s) installed: ${BOLD}${REQUIREMENTS}${RESET_COLORS}"
				exit 1
		fi
fi
