#!/bin/bash
## Search for a keyword on pastebin with Google dorks.

RED="\e[31m"
CYAN="\e[36m"
BOLD="\e[1m"
RESET_COLOR="\e[0m"

## <Google dorks URL> + <keyword>
REQUEST="https://www.google.com/search?q=site:'pastebin.com'%20intext:'${1}'"

if [[ ${1} ]]
	then
		x-www-browser ${REQUEST} 2>/dev/null&
		echo -e "Searching for ${BOLD}${CYAN}${1}${RESET_COLOR}..."
	else
		echo -e "${RED}Please, enter a term to search on Pastebin (e.g. 'cars').${RESET_COLOR}"
fi
