#!/bin/bash
## Randomly play videos from a youtube channel.

RC="\e[0m"
UL="\e[4m"
BOLD="\e[1m"
GREY="${BOLD}\e[37m"
RED="${BOLD}\e[31m"
YELLOW="${BOLD}\e[33m"
BLUE="${BOLD}\e[34m"

REQUIREMENTS="mpv yt-dlp"

if ! which ${REQUIREMENTS}>/dev/null
	then
		echo -e "${RED}You need ${REQUIREMENTS} to run this script!${RC}"
		exit 1
fi

## Eelf.
channel_[1]="https://www.youtube.com/c/EELFtrax"
## Eelf records.
channel_[2]="https://www.youtube.com/c/EELFRECORDS"
## Theuppermostinlife
channel_[3]="https://www.youtube.com/c/theuppermostinlife"
## Houseum
channel_[4]="https://www.youtube.com/c/Houseum"
## Slav
channel_[5]="https://www.youtube.com/c/SlavRecords"
## CMYK
channel_[6]="https://www.youtube.com/c/CMYKitsme"

selectionMenu()
{
	echo -e "\n ${UL}${YELLOW}Select a channel:${RC}\n\n \
${BLUE}[${RC}1${BLUE}] ${RC}Eelf${RC}\n \
${BLUE}[${RC}2${BLUE}] ${RC}Eelf Records${RC}\n \
${BLUE}[${RC}3${BLUE}] ${RC}The Uppermost In Life${RC}\n \
${BLUE}[${RC}4${BLUE}] ${RC}Houseum${RC}\n \
${BLUE}[${RC}5${BLUE}] ${RC}Slav${RC}\n \
${BLUE}[${RC}6${BLUE}] ${RC}CMYK${RC}\n\n \
${BLUE}[${GREY}?${BLUE}] ${GREY}Display player shortcut.${RC}\n "
}

displayShortcut()
{
	echo -e "\n ${BLUE}<${GREY}SPACE${BLUE}>${RC}	pause.\n \
${BLUE}<${GREY}ENTER${BLUE}>${RC}	skip.\n \
${BLUE}<${GREY}M${BLUE}>${RC}		mute.\n
${BLUE}<${GREY}Q${BLUE}>${RC}		quit.\n"
}

main()
{
	clear
	selectionMenu
	read -s -n 1 selectedChannel
	case ${selectedChannel} in
		[0-9])
			currentlyPlaying=$(echo "${channel_[${selectedChannel}]}"|cut -d "/" -f 5)
			clear
			echo -e "\n ${YELLOW}Playing ${currentlyPlaying}...${RC}\n"
			mpv --shuffle --no-video "${channel_[${selectedChannel}]}"
			;;
		?)
			clear
			displayShortcut
			;;
		*)
			clear
			echo -e "${RED}Please enter a valid number!${RC}"
			exit 1
			;;
	esac
}

main
