#!/bin/bash
## Play your favorites songs without leaving the tty.

## Youtube channels:
## - Eelf.
channel_[1]="https://www.youtube.com/c/EELFtrax"
## - Eelf records.
channel_[2]="https://www.youtube.com/c/EELFRECORDS"
## - The Uppermost In Life
channel_[3]="https://www.youtube.com/c/theuppermostinlife"
## - Houseum
channel_[4]="https://www.youtube.com/c/Houseum"
## - Slav
channel_[5]="https://www.youtube.com/c/SlavRecords"
## - CMYK
channel_[6]="https://www.youtube.com/c/CMYKitsme"

## Colors.
RC="\e[0m"
UL="\e[4m"
BOLD="\e[1m"
GREY="\e[37m"
RED="$\e[31m"
YELLOW="\e[33m"
BLUE="\e[34m"

selectionMenu()
{
	clear
	echo -e "\n ${UL}${YELLOW}Select a channel:${RC}\n\n \
${BLUE}[${RC}1${BLUE}] ${RC}Eelf${RC}\n \
${BLUE}[${RC}2${BLUE}] ${RC}Eelf Records${RC}\n \
${BLUE}[${RC}3${BLUE}] ${RC}The Uppermost In Life${RC}\n \
${BLUE}[${RC}4${BLUE}] ${RC}Houseum${RC}\n \
${BLUE}[${RC}5${BLUE}] ${RC}Slav${RC}\n \
${BLUE}[${RC}6${BLUE}] ${RC}CMYK${RC}\n\n \
${BLUE}[${GREY}?${BLUE}] ${GREY}Display player shortcut.${RC}\n "
}

displayShortcut()
{
	clear
	echo -e "\n ${BLUE}<${GREY}SPACE${BLUE}>${RC}	pause.\n \
${BLUE}<${GREY}ENTER${BLUE}>${RC}	skip.\n \
${BLUE}<${GREY}M${BLUE}>${RC}		mute.\n \
${BLUE}<${GREY}Q${BLUE}>${RC}		quit.\n\n \
Try ${BLUE}'${BOLD}${GREY}man mpv${BLUE}'${RC} for more informations.${RC}"
}

displayRequirements()
{
	clear
	echo -e "\n ${UL}${RED}To run this program you need:${RC}\n\n \
- mpv\n \
- cava/vis\n \
- youtube-dl/yt-dlp\n"
}

checkRequirements()
{
	downloader=$(which yt-dlp youtube-dl | grep -v "not found" | head -n1)
	visualizer=$(which vis cava | grep -v "not found" | head -n1)

	if [[ ${downloader} == "" || ${visualizer} == "" ]]
		then
			displayRequirements
			exit 1
	fi

	if ! which mpv>/dev/null
		then
			displayRequirements
			exit 1
	fi
}

main()
{
	checkRequirements
	selectionMenu
	read -s -n 1 selectedChannel
	case ${selectedChannel} in
		[0-9])
			currentlyPlaying=$(echo "${channel_[${selectedChannel}]}"|cut -d "/" -f 5)
			clear
			echo -e "\n ${YELLOW}Playing ${currentlyPlaying}...${RC}\n"
			mpv --shuffle --no-video "${channel_[${selectedChannel}]}"
			;;
		?)
			displayShortcut
			read
			main
			;;
		*)
			clear
			echo -e "${RED}Please enter a valid number!${RC}"
			exit 1
			;;
	esac
}
main
