#!/bin/bash

if [[ ${1} ]]
	then
		echo $(cat /dev/random | tr -dc 'a-zA-Z0-9!?@#$%^&*"^_+=><~`:;.' | head -c ${1})
#		echo -e "$(cat /dev/random | tr -cd 'a-z0-9' | head -c ${1})\n"
	else
		echo $(cat /dev/random | tr -dc 'a-zA-Z0-9!?@#$%^&*"^_+=><~`:;.' | head -c 16)
#		echo -e "$(cat /dev/random | tr -cd 'a-z0-9' | head -c 16)\n"
fi
