#!/bin/bash
HOST="thinkpad"
echo "Password:"

if ! xfreerdp > /dev/null
	then
		echo "xfreerdp is not installed!"
		exit 1
	else
		read -s PASS
		xfreerdp \
			/v:${HOST} \
			/u:lespink \
			/p:${PASS} \
			/f \
			/cert-ignore \
			/compression-level:9 \
			+aero \
			+auto-reconnect
fi
