#!/usr/bin/env bash
## Search for a specific program, and print it's man pages into a pdf reader.

DMENU="rofi"
DMENU_CMD="rofi -dmenu"
PDF_READER="atril"
PDF_CMD="atril -f"

MAN_PAGE=$(man -k .|cut -d " " -f 1|${DMENU_CMD})
OUT_FILE="/tmp/${MAN_PAGE}_man.pdf"
REQUIREMENTS="man ${PDF_READER} ${DMENU}"

if ! which ${REQUIREMENTS}>/dev/null
    then
        echo "To run this program, you need: ${REQUIREMENTS}!"
        exit 1
fi

[[ ! ${MAN_PAGE} ]] && exit
man -T pdf ${MAN_PAGE}>${OUT_FILE}
${PDF_CMD} ${OUT_FILE}
rm ${OUT_FILE}
