#!/bin/bash
## Verify if a Telegram user exist.
## Currently reporting false positive (name with only numbers and/or containing special characters).

RESET_COLOR="\e[0m"
BOLD="\e[1m"
BLUE="\e[34m"
RED="\e[31m"
GREEN="\e[32m"
CYAN="\e[36m"
UNDERLINE="\e[4m"
ITALIC="\e[3m"

REQUIREMENTS="curl"
TG_LINK="https://t.me/"
TG_USER="${1}"

DISPLAY_HELP()
{
	echo -e "${CYAN}${ITALIC}Check if a Telegram username is valid.\n${RESET_COLOR}"
	echo -e "${UNDERLINE}Usage:${RESET_COLOR}"
	echo -e " ./tguser <username>\n${RESET_COLOR}"
}

REQUEST=$(curl -sf "${TG_LINK}/${TG_USER}" | grep "og:description")
NO_DESCRIPTION='<meta property="og:description" content="">'

function CHECK_USER()
{
	## Check if the user have a descritption (Telegram automatically add one if the user don't).
	if [[ ${REQUEST} != ${NO_DESCRIPTION} ]]
		then
			echo -e "${BOLD}${GREEN} [+] ${RESET_COLOR}User ${BOLD}${TG_USER}${RESET_COLOR} found!${RESET_COLOR}"
		else
			echo -e "${BOLD}${RED} [-] ${RESET_COLOR}User ${BOLD}${TG_USER}${RESET_COLOR} not found!${RESET_COLOR}"
	fi
}

which ${REQUIREMENTS}>/dev/null

if [[ ${?} -eq "0" ]]
	then
		if [[ ${1} ]]
			then
				CHECK_USER
			else
				DISPLAY_HELP
		fi
	else
		echo -e "${RED}To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}\nExiting...${RESET_COLORS}"
		exit 1
fi
