#!/bin/bash

## Set colors.
RC="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"
BLUE="\e[34m"

WARN="${RED}${BOLD} [-] ${RC}"
INFO="${BLUE}${BOLD} [*] ${RC}"
GOOD="${GREEN}${BOLD} [+] ${RC}"

REQUIREMENTS="shred zip" ## And a CLI editor of your choice.

ENCRYPTED_FILE="${HOME}/.todo.zip"
DECRYPTED_FILE="${HOME}/.todo"

RUN()
{
	## Prompt for the password.
	echo "Password:"
	read -s PASSWORD
	## Decrypt the files.
	unzip -P "${PASSWORD}" ${ENCRYPTED_FILE}
	[ ${?} -ne '0' ] && exit 1
	## Edit the files.
	${EDITOR} ${DECRYPTED_FILE}
	## Create the archive.
	shred -fuzv ${ENCRYPTED_FILE}
	zip -vr -P "${PASSWORD}" ${ENCRYPTED_FILE} ${DECRYPTED_FILE}
	## Remove the decrypted file.
	shred -fuzv ${DECRYPTED_FILE}
}

if [[ -f ${ENCRYPTED_FILE} ]]
	then
		if ! which ${REQUIREMENTS} > /dev/null
			then
				echo -e "${WARN}To run this program, you need the following packages installed: ${REQUIREMENTS}\n${WARN}Exiting..."
			else
				RUN
		fi
	else
		echo -e "${INFO}Note file note not found, do you want to create one? (Y/n)"
		read -s -n 1 CREATE_DECRYPTED_FILE
			case ${CREATE_DECRYPTED_FILE} in
				Y/y)
					RUN
					;;
				*)
					echo  -e "${GOOD}Exiting..."
					exit 1
					;;
			esac
fi
