#!/bin/bash
# .:: Google Translate the words supplied ::. #

if [[ ${1} == "-en" ]]
	then
		firefox --new-window "https://translate.google.com/?sl=auto&tl=en&text=${2}&op=translate"
	else
		firefox --new-window "https://translate.google.com/?sl=auto&tl=fr&text=${1}&op=translate"
fi
