#!/bin/bash
# Update my git repository
clear

# Check if root
if [ "$EUID" -ne 0 ]
	then
		echo -e "${RED}This script must be runned as root${RESET_COLOR}"
		exit
fi

# Set color
GREEN="\e[32m"
RED="\e[31m"
RESET_COLOR="\e[0m"

CWD=$(pwd)
USER="lespink"
REPO_DIR=/opt/utilities

ls ~/.git-credentials 2>/dev/null
if [[ ${?} -eq 0 ]]
	then
		# Add the change to the repo
		cd ${REPO_DIR}
		git pull
		git add -v .*
		git add -v *
		cd dot-files
		git add -v *
		git add -v .*
		git commit -a
		git push -v
	else
		echo -e "${RED}Git credentials not found !${RESET_COLOR}"
fi

# Make symbolic link
cd ${REPO_DIR}
ln -vf * /bin
cd dot-files
ln -vf .* /home/$USER
ln -vf .* /root

cd ${CWD}

echo -e "${GREEN}Your files and git repository has been updated successfully !${RESET_COLOR}\e[0m"
