#!/bin/bash
# .:: Update the system ::. #

clear
HOSTNAME_COLOR=$(cat ~/.hostname_color)

function UPDATE_APT()
{
	apt clean -y
	apt autoclean -y
	apt autoremove --purge -y

	dpkg --configure -a
	apt --fix-broken install

	apt update
	apt upgrade -y --with-new-pkgs

	apt update
	apt dist-upgrade -y --ignore-hold

	apt update
	apt full-upgrade -y

	dpkg --configure -a
	apt --fix-broken install

	apt clean -y
	apt autoclean -y
	apt autoremove --purge -y

}

function UPDATE_NPM()
{
	npm audit
	npm doctor
	npm update
	cat /root/.npm/_logs/* | ccze -A
	mv -vf /root/.npm/_logs/* /root/*.json ~/.trash
}

WORKSPACE=/


# Kill the "enter username prompt" when git pull
function NO_INPUT()
{
	if [[ -t 0 ]]
		then
			stty -echo -icanon time 0 min 0
	fi
}

function UPDATE_GIT()
{
	cd ${WORKSPACE}
	for GIT_PATH in $(find ${WORKSPACE} -type d -name ".git")
		do
			cd ${GIT_PATH};
			echo -e "\n\e[34m\e[1m${GIT_PATH}\e[0m"
			cd ..
			git config pull.rebase false
			git stash
			git pull
			cd ${WORKSPACE}
		done
}

function UPDATE_KERNEL()
{
	if [[ ${HOSTNAME_COLOR} == "red" ]]
		then
			cp -vur /opt/FIRMWARE/linux-firmware/* /lib/firmware
			cp -vur /opt/FIRMWARE/unofficial-amdgpu-firmware-repo/amdgpu/* /lib/firmware/amdgpu
			update-initramfs -du
		else
			cp -vur /opt/FIRMWARE/linux-firmware/* /lib/firmware
			update-initramfs -du
	fi
}

function TRASH_LOG()
{
	mkdir -p ~/.trash
	mv -vf $(find / -type f -name "*.log") ~/.trash
	mv -vf $(find / -type f -name "*.log*") ~/.trash

	mv -vf $(find / -type f -name "*.old") ~/.trash
	mv -vf $(find / -type f -name "*.old*") ~/.trash

	mv -vf /var/log/journal/* ~/.trash
}

echo -e "\e[35m\e[1m$(date +%H:%M:%S)\e[0m"
echo -e "\e[33mUpdating \e[1mAPT\e[0m \e[33mpackages...\e[0m"
UPDATE_APT | ccze -A
echo -e "\e[32mDone!\e[0m"

echo -e "\e[35m\e[1m$(date +%H:%M:%S)\e[0m"
echo -e "\e[33mUpdating \e[1mGIT\e[0m \e[33mrepositories...\e[0m"
UPDATE_GIT
echo -e "\e[32mDone!\e[0m"

echo -e "\e[35m\e[1m$(date +%H:%M:%S)\e[0m"
echo -e "\e[33mUpdating \e[1mNPM\e[0m \e[33mpackages...\e[0m"
#UPDATE_NPM
echo -e "\e[32mDone!\e[0m"

echo -e "\e[35m\e[1m$(date +%H:%M:%S)\e[0m"
echo -e "\e[33mUpdating \e[1mkernel\e[0m \e[33m...\e[0m"
UPDATE_KERNEL
echo -e "\e[32mDone!\e[0m"

echo -e "\e[35m\e[1m$(date +%H:%M:%S)\e[0m"
echo -e "\e[33mSearching for \e[1mlogs\e[0m \e[33mto \e[1mtrash\e[0m\e[33m...\e[0m"
TRASH_LOG
echo -e "\e[32mDone!\e[0m"

