#!/bin/bash

CWD=$(pwd)
REPO_DIR=/opt/utilities

cd ${REPO_DIR}

ln -f * /bin
cd dot-files
ln -f .zshrc ~

cd ${REPO_DIR}
git add -v * | ccze -A
git commit
git push -v | ccze -A

cd ${CWD}

echo -e "\e[32mDone!\e[0m"
