#!/bin/bash
# Update my git repository

CWD=$(pwd)
REPO_DIR=/opt/utilities

cd ${REPO_DIR}
git pull
git add -v * | ccze -A
git commit -a
git push -v | ccze -A

ln -f * /bin
cd dot-files
ln -f .zshrc ~

cd ${CWD}

echo -e "\e[32mDone!\e[0m"
