#!/bin/bash
## Download wallpapers from https://wallhaven.cc
## Heavily inspired by BugsWriter video's (https://www.youtube.com/watch?v=Ol3g0Rp0XkM)
## TODO: Remove the brighter ones?

RESET_COLOR="\e[0m"
GREEN="\e[32m"
YELLOW="\e[33m"
RED="\e[31m"
BOLD="\e[1m"

REQUIREMENTS="curl jq notify-send"

WALLPAPERS_DIR="${HOME}/Pictures/Backgrounds/WallHaven"
MIN_RESOLUTION="1920x1080"
SORT_OPTIONS="relevance" ## date_added relevance random views favorites toplist.
QUERY="${1}"
PAGE=$(shuf -i 1-2748 | head -n1) ## 2748 pages for "girl" in anime (02/08/2021).
## Turn categories on(1) or off(0).
CATEGORY="010" ## 100/101/111*/etc (general/anime/people).
## Turn purities on(1) or off(0) NSFW requires a valid API key.
PURITY="110" ##100*/110/111/etc (sfw/sketchy/nsfw).

## Change input to URL format.
QUERY="$(sed 's/#//g' <<<${QUERY})"
QUERY="$(sed 's/ /+/g' <<<${QUERY})"

mkdir -p ${WALLPAPERS_DIR}/${QUERY}

URL="https://wallhaven.cc/api/v1/search?q=${QUERY}&categories=${CATEGORIES}&purity=${PURITY}&sorting=${SORT_OPTIONS}&order=desc&page=${PAGE}"
REGEX_FILTER='https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b'

function REQUEST()
{
	curl -sf "https://wallhaven.cc/api/v1/search?q=${QUERY}&categories=${CATEGORY}&purity=${PURITY}&sorting=${SORT_OPTIONS}&order=desc&page=${PAGE}"\
	| jq '.' | grep -Eoh 'https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b'\
	| xargs -l wget -nc -nv -P ${WALLPAPERS_DIR}/${QUERY}
}

if [[ ${1} ]]
	then
		which ${REQUIREMENTS} > /dev/null
		if [[ ${?} -eq "0" ]]
			then
				echo -e " 🔎 ${YELLOW}Searching for ${QUERY} wallpapers...${RESET_COLOR}"
				REQUEST
				notify-send " ✅ Downloads finished!... "
				echo -e "${YELLOW}Open the wallpaper directory? (N/y)${RESET_COLOR}"
				read -s CHOOSE_WALLPAPER
					if [[ ${CHOOSE_WALLPAPER} == "y" ]]
						then
							which thunar > /dev/null
								if [[ ${?} -eq "0" ]]
									then
										thunar ${WALLPAPERS_DIR}/${QUERY} > /dev/null
									else
										echo "You'r probably not on XFCE!\Quitting..."
								fi
						else
							exit 0
					fi
			else
				echo -e "${RED}To run this program, you need the following packages installed: ${BOLD}${REQUIREMENTS}${RESET_COLORS}"
				exit 1
		fi
	else
		echo -e "${RED}Please, provides a topics for your images (e.g. Cars)"
fi
